name: NixOS Build Test

on:
  # Trigger the workflow on push or pull request events in any branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of os the job will run on (can't do images directly yet)
    runs-on: ubuntu-latest

    # Instead image is brought in here
    container:
      image: docker://nixos/nix

    steps:
      # Run a set of commands using the runners shell
      - name: Dry-run build to verify
        run: |
          nix flake check --impure github:sammypanda/nixos-config

